### ISSUE TITLE
Fix the Kubernetes Deployment?

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#129] opened 2021-06-16 18:27 UTC
I receive an `Internal Server Error` when trying to access the endpoints except `Standup` when accessing the Kubernetes Version

**Comment by eddiejaoude** [comment] 2021-06-23 07:58
I think the issue is because there is no `namespace` created

**Comment by eddiejaoude** [comment] 2021-06-23 08:28
Even when the `namespace` is created, but there is no collection, a `500` is still thrown

**Comment by eddiejaoude** [comment] 2021-06-23 09:00
Now there is a `namespace` and a collection `standup`, the endpoint api.eddiehub.org/standup returns the result

```json
{
  "214d9793-5c6b-47e4-a787-ee28b10b763e": {
    "author": {
      "platform": "discord",
      "uid": "test"
    },
    "createdOn": "2021-06-08T22:35:09.409Z",
    "todayMessage": "today message",
    "yesterdayMessage": "yesterday message"
  },
  "17dac948-1ee4-4064-a4d6-619c28fb5c26": {
    "author": {
      "platform": "discord",
      "uid": "test"
    },
    "createdOn": "2021-06-08T22:58:47.363Z",
    "todayMessage": "today message 3",
    "yesterdayMessage": "yesterday message 3"
  },
  "43f17eee-dcff-46ac-8e14-bb2359744d2e": {
    "author": {
      "platform": "discord",
      "uid": "test"
    },
    "createdOn": "2021-06-08T22:58:14.737Z",
    "todayMessage": "today message 2",
    "yesterdayMessage": "yesterday message 2 "
  }
}
```

**Comment by eddiejaoude** [comment] 2021-07-26 23:32
I think this is fixed now

**Closed by eddiejaoude** 2021-07-26 23:32 UTC
Labels: 🏁 status: ready for dev, 💻 aspect: code, 🔢 points: 3, 🟥 priority: critical
